# Generated by Django 5.0.7 on 2025-08-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonrequest",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
